name: wefood
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-167.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  flutter_secure_storage: ^9.0.0
  get: ^4.6.6
  google_maps_flutter: ^2.5.0
  http: ^1.2.1
  # location:
  maps_launcher: ^2.2.1
  permission_handler: ^11.3.0
  share_plus: ^7.0.2
  sign_in_button: ^3.2.0
  syncfusion_flutter_pdfviewer: ^24.2.8
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/documents/terms_and_conditions.pdf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700