name: wefood
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-167.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_secure_storage: ^9.0.0
  geolocator: ^11.0.0
  get: ^4.6.6
  get_it: ^7.7.0
  google_maps_flutter: ^2.5.0
  http: ^1.2.1
  image_picker: ^1.1.0
  maps_launcher: ^2.2.1
  mobile_scanner: ^1.0.0
  permission_handler: ^11.3.0
  share_plus: ^7.0.2
  sign_in_button: ^3.2.0
  syncfusion_flutter_pdfviewer: ^24.2.8
  url_launcher: ^6.2.6
  qr_flutter: ^4.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/documents/terms_and_conditions.pdf